### PR TITLE
readonly and writeonly properties

### PR DESCRIPTION
**Pull request by lucasfcardozo**
Adds the possibility of a property to be readOnly or writeOnly

### CODE REVIEW

**Comment by rduldulao** [comment]
HI @lucasfcardozo , will put your suggestion under consideration.  There is one more place to put schema properties though:

`
    docstring = """Test schema
    This is something
    Properties:
        id (int) -- Required. The id.
            readOnly: true  minimum: 1
    """
`

**Comment by lucasfcardozo** [comment]
thanks

**Comment by rduldulao** [comment]
edited the code formatting of my example.  didnt come out right the first time

**Comment by lucasfcardozo** [comment]
Thank you so much, @rduldulao, for showing the right way. 

Reviewing the code, I would suggest to add ' readOnly ' and ' writeOnly ' in `_PROPS_TYPE_LOOKUP ['Boolean']`. What do you think?

`_PROPS_TYPE_LOOKUP = {
    Boolean: ('exclusiveMinimum', 'exclusiveMaximum', 'uniqueItems',
              'allowEmptyValue', 'deprecated', 'readOnly', 'writeOnly'),
    Number: ('minimum', 'maximum', 'multipleOf', 'minItems',
             'maxItems', 'maxLength', 'minLength', 'uniqueItems',
             'minProperties', 'maxProperties')
}`

**Pull request closed without merging**
